// Date: 7/1/2014 2:45:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.johngalt.gulch.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GaltModelBellow extends ModelBase
{
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape22;
    ModelRenderer a3;
    ModelRenderer a4;
    ModelRenderer Shape2a5;
    ModelRenderer Shape2a6;
    ModelRenderer Shape1a7;
    ModelRenderer Shape2a8;
    ModelRenderer Shape2a9;
    ModelRenderer Shape2aa1;
    ModelRenderer Shape2aa2;
    ModelRenderer Shape2aa3;
    ModelRenderer Shape2aa4;
    ModelRenderer Shape3a5a5;
    ModelRenderer Shape4aa6;
    ModelRenderer Shape4aa7;
    ModelRenderer Shape4aa8;
    ModelRenderer Shape4aa9;
    ModelRenderer Shape4o1;
    ModelRenderer Shape4oo2;
    ModelRenderer Shape4o3;
    ModelRenderer Shape4o4;
    ModelRenderer Shape4o5;
    ModelRenderer Shape4o6;
    ModelRenderer Shape4o7;
    ModelRenderer Shape4o8;
    ModelRenderer Shape4o9;
    ModelRenderer Shape4e1;
    ModelRenderer Shape4e2;

    public GaltModelBellow()
    {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 30);
        Shape1.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape1.setRotationPoint(4F, 22F, -1F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape22 = new ModelRenderer(this, 0, 11);
        Shape22.addBox(0F, 0F, 0F, 2, 1, 14);
        Shape22.setRotationPoint(2F, 22F, -7F);
        Shape22.setTextureSize(64, 32);
        Shape22.mirror = true;
        setRotation(Shape22, 0F, 0F, 0F);
        a3 = new ModelRenderer(this, 0, 11);
        a3.addBox(0F, 0F, 0F, 2, 1, 12);
        a3.setRotationPoint(0F, 21F, -6F);
        a3.setTextureSize(64, 32);
        a3.mirror = true;
        setRotation(a3, 0F, 0F, 0F);
        a4 = new ModelRenderer(this, 0, 11);
        a4.addBox(0F, 0F, 0F, 2, 1, 10);
        a4.setRotationPoint(-2F, 20F, -5F);
        a4.setTextureSize(64, 32);
        a4.mirror = true;
        setRotation(a4, 0F, 0F, 0F);
        Shape2a5 = new ModelRenderer(this, 0, 11);
        Shape2a5.addBox(0F, 0F, 0F, 2, 1, 8);
        Shape2a5.setRotationPoint(-4F, 19F, -4F);
        Shape2a5.setTextureSize(64, 32);
        Shape2a5.mirror = true;
        setRotation(Shape2a5, 0F, 0F, 0F);
        Shape2a6 = new ModelRenderer(this, 0, 11);
        Shape2a6.addBox(0F, 0F, 0F, 2, 1, 4);
        Shape2a6.setRotationPoint(-6F, 18F, -2F);
        Shape2a6.setTextureSize(64, 32);
        Shape2a6.mirror = true;
        setRotation(Shape2a6, 0F, 0F, 0F);
        Shape1a7 = new ModelRenderer(this, 0, 30);
        Shape1a7.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape1a7.setRotationPoint(4F, 12F, -1F);
        Shape1a7.setTextureSize(64, 32);
        Shape1a7.mirror = true;
        setRotation(Shape1a7, 0F, 0F, 0F);
        Shape2a8 = new ModelRenderer(this, 0, 11);
        Shape2a8.addBox(0F, 0F, 0F, 2, 1, 14);
        Shape2a8.setRotationPoint(2F, 12F, -7F);
        Shape2a8.setTextureSize(64, 32);
        Shape2a8.mirror = true;
        setRotation(Shape2a8, 0F, 0F, 0F);
        Shape2a9 = new ModelRenderer(this, 0, 0);
        Shape2a9.addBox(0F, 0F, 0F, 2, 1, 2);
        Shape2a9.setRotationPoint(-8F, 17F, -1F);
        Shape2a9.setTextureSize(64, 32);
        Shape2a9.mirror = true;
        setRotation(Shape2a9, 0F, 0F, 0F);
        Shape2aa1 = new ModelRenderer(this, 0, 11);
        Shape2aa1.addBox(0F, 0F, 0F, 2, 1, 12);
        Shape2aa1.setRotationPoint(0F, 13F, -6F);
        Shape2aa1.setTextureSize(64, 32);
        Shape2aa1.mirror = true;
        setRotation(Shape2aa1, 0F, 0F, 0F);
        Shape2aa2 = new ModelRenderer(this, 0, 11);
        Shape2aa2.addBox(0F, 0F, 0F, 2, 1, 10);
        Shape2aa2.setRotationPoint(-2F, 14F, -5F);
        Shape2aa2.setTextureSize(64, 32);
        Shape2aa2.mirror = true;
        setRotation(Shape2aa2, 0F, 0F, 0F);
        Shape2aa3 = new ModelRenderer(this, 0, 11);
        Shape2aa3.addBox(0F, 0F, 0F, 2, 1, 8);
        Shape2aa3.setRotationPoint(-4F, 15F, -4F);
        Shape2aa3.setTextureSize(64, 32);
        Shape2aa3.mirror = true;
        setRotation(Shape2aa3, 0F, 0F, 0F);
        Shape2aa4 = new ModelRenderer(this, 0, 11);
        Shape2aa4.addBox(0F, 0F, 0F, 2, 1, 4);
        Shape2aa4.setRotationPoint(-6F, 16F, -2F);
        Shape2aa4.setTextureSize(64, 32);
        Shape2aa4.mirror = true;
        setRotation(Shape2aa4, 0F, 0F, 0F);
        Shape3a5a5 = new ModelRenderer(this, 38, 0);
        Shape3a5a5.addBox(0F, 0F, 0F, 1, 9, 12);
        Shape3a5a5.setRotationPoint(3F, 13F, -6F);
        Shape3a5a5.setTextureSize(64, 32);
        Shape3a5a5.mirror = true;
        setRotation(Shape3a5a5, 0F, 0F, 0F);
        Shape4aa6 = new ModelRenderer(this, 16, 0);
        Shape4aa6.addBox(0F, 0F, 0F, 2, 1, 4);
        Shape4aa6.setRotationPoint(-6F, 17F, -2F);
        Shape4aa6.setTextureSize(64, 32);
        Shape4aa6.mirror = true;
        setRotation(Shape4aa6, 0F, 0F, 0F);
        Shape4aa7 = new ModelRenderer(this, 16, 0);
        Shape4aa7.addBox(0F, 0F, 0F, 1, 9, 1);
        Shape4aa7.setRotationPoint(2F, 13F, -5F);
        Shape4aa7.setTextureSize(64, 32);
        Shape4aa7.mirror = true;
        setRotation(Shape4aa7, 0F, 0F, 0F);
        Shape4aa8 = new ModelRenderer(this, 16, 0);
        Shape4aa8.addBox(0F, 0F, 0F, 1, 7, 1);
        Shape4aa8.setRotationPoint(1F, 14F, -5F);
        Shape4aa8.setTextureSize(64, 32);
        Shape4aa8.mirror = true;
        setRotation(Shape4aa8, 0F, 0F, 0F);
        Shape4aa9 = new ModelRenderer(this, 16, 0);
        Shape4aa9.addBox(0F, 0F, 0F, 1, 7, 1);
        Shape4aa9.setRotationPoint(0F, 14F, -5F);
        Shape4aa9.setTextureSize(64, 32);
        Shape4aa9.mirror = true;
        setRotation(Shape4aa9, 0F, 0F, 0F);
        Shape4o1 = new ModelRenderer(this, 16, 0);
        Shape4o1.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape4o1.setRotationPoint(-1F, 15F, -5F);
        Shape4o1.setTextureSize(64, 32);
        Shape4o1.mirror = true;
        setRotation(Shape4o1, 0F, 0F, 0F);
        Shape4oo2 = new ModelRenderer(this, 16, 0);
        Shape4oo2.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape4oo2.setRotationPoint(-2F, 15F, -4F);
        Shape4oo2.setTextureSize(64, 32);
        Shape4oo2.mirror = true;
        setRotation(Shape4oo2, 0F, 0F, 0F);
        Shape4o3 = new ModelRenderer(this, 16, 0);
        Shape4o3.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape4o3.setRotationPoint(-4F, 16F, -3F);
        Shape4o3.setTextureSize(64, 32);
        Shape4o3.mirror = true;
        setRotation(Shape4o3, 0F, 0F, 0F);
        Shape4o4 = new ModelRenderer(this, 16, 0);
        Shape4o4.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape4o4.setRotationPoint(-3F, 16F, -4F);
        Shape4o4.setTextureSize(64, 32);
        Shape4o4.mirror = true;
        setRotation(Shape4o4, 0F, 0F, 0F);
        Shape4o5 = new ModelRenderer(this, 16, 0);
        Shape4o5.addBox(0F, 0F, 0F, 1, 9, 1);
        Shape4o5.setRotationPoint(2F, 13F, 4F);
        Shape4o5.setTextureSize(64, 32);
        Shape4o5.mirror = true;
        setRotation(Shape4o5, 0F, 0F, 0F);
        Shape4o6 = new ModelRenderer(this, 16, 0);
        Shape4o6.addBox(0F, 0F, 0F, 1, 7, 1);
        Shape4o6.setRotationPoint(0F, 14F, 4F);
        Shape4o6.setTextureSize(64, 32);
        Shape4o6.mirror = true;
        setRotation(Shape4o6, 0F, 0F, 0F);
        Shape4o7 = new ModelRenderer(this, 16, 0);
        Shape4o7.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape4o7.setRotationPoint(-1F, 15F, 4F);
        Shape4o7.setTextureSize(64, 32);
        Shape4o7.mirror = true;
        setRotation(Shape4o7, 0F, 0F, 0F);
        Shape4o8 = new ModelRenderer(this, 16, 0);
        Shape4o8.addBox(0F, 0F, 0F, 1, 5, 1);
        Shape4o8.setRotationPoint(-2F, 15F, 3F);
        Shape4o8.setTextureSize(64, 32);
        Shape4o8.mirror = true;
        setRotation(Shape4o8, 0F, 0F, 0F);
        Shape4o9 = new ModelRenderer(this, 16, 0);
        Shape4o9.addBox(0F, 0F, 0F, 1, 7, 1);
        Shape4o9.setRotationPoint(1F, 14F, 4F);
        Shape4o9.setTextureSize(64, 32);
        Shape4o9.mirror = true;
        setRotation(Shape4o9, 0F, 0F, 0F);
        Shape4e1 = new ModelRenderer(this, 16, 0);
        Shape4e1.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape4e1.setRotationPoint(-3F, 16F, 3F);
        Shape4e1.setTextureSize(64, 32);
        Shape4e1.mirror = true;
        setRotation(Shape4e1, 0F, 0F, 0F);
        Shape4e2 = new ModelRenderer(this, 16, 0);
        Shape4e2.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape4e2.setRotationPoint(-4F, 16F, 2F);
        Shape4e2.setTextureSize(64, 32);
        Shape4e2.mirror = true;
        setRotation(Shape4e2, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape22.render(f5);
        a3.render(f5);
        a4.render(f5);
        Shape2a5.render(f5);
        Shape2a6.render(f5);
        Shape1a7.render(f5);
        Shape2a8.render(f5);
        Shape2a9.render(f5);
        Shape2aa1.render(f5);
        Shape2aa2.render(f5);
        Shape2aa3.render(f5);
        Shape2aa4.render(f5);
        Shape3a5a5.render(f5);
        Shape4aa6.render(f5);
        Shape4aa7.render(f5);
        Shape4aa8.render(f5);
        Shape4aa9.render(f5);
        Shape4o1.render(f5);
        Shape4oo2.render(f5);
        Shape4o3.render(f5);
        Shape4o4.render(f5);
        Shape4o5.render(f5);
        Shape4o6.render(f5);
        Shape4o7.render(f5);
        Shape4o8.render(f5);
        Shape4o9.render(f5);
        Shape4e1.render(f5);
        Shape4e2.render(f5);
    }

    public void renderModel(float f5)
    {
        Shape1.render(f5);
        Shape22.render(f5);
        a3.render(f5);
        a4.render(f5);
        Shape2a5.render(f5);
        Shape2a6.render(f5);
        Shape1a7.render(f5);
        Shape2a8.render(f5);
        Shape2a9.render(f5);
        Shape2aa1.render(f5);
        Shape2aa2.render(f5);
        Shape2aa3.render(f5);
        Shape2aa4.render(f5);
        Shape3a5a5.render(f5);
        Shape4aa6.render(f5);
        Shape4aa7.render(f5);
        Shape4aa8.render(f5);
        Shape4aa9.render(f5);
        Shape4o1.render(f5);
        Shape4oo2.render(f5);
        Shape4o3.render(f5);
        Shape4o4.render(f5);
        Shape4o5.render(f5);
        Shape4o6.render(f5);
        Shape4o7.render(f5);
        Shape4o8.render(f5);
        Shape4o9.render(f5);
        Shape4e1.render(f5);
        Shape4e2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
