package com.johngalt.gulch.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GaltMoldStationModel extends ModelBase
{
    //fields
    ModelRenderer Table;
    ModelRenderer Leg2Shaft1;
    ModelRenderer Leg2Shaft2;
    ModelRenderer Leg2Shaft3;
    ModelRenderer Leg2Shaft4;
    ModelRenderer Leg4Shaft3;
    ModelRenderer Leg4Shaft2;
    ModelRenderer Leg4Shaft;
    ModelRenderer Leg4Shaft4;
    ModelRenderer Leg2Shaft;
    ModelRenderer Leg4Shaft1;
    ModelRenderer Leg1Shaft1;
    ModelRenderer Leg1Shaft;
    ModelRenderer Leg1Shaft2;
    ModelRenderer Leg1Shaft4;
    ModelRenderer Leg1Shaft3;
    ModelRenderer Leg3Shaft1;
    ModelRenderer Leg3Shaft;
    ModelRenderer Leg3Shaft2;
    ModelRenderer Leg3Shaft3;
    ModelRenderer Leg3Shaft4;
    ModelRenderer BottomMold3;
    ModelRenderer TopMold;
    ModelRenderer BottomMold;
    ModelRenderer BottomMold1;
    ModelRenderer BottomMold2;
    ModelRenderer BottomMold4;
    ModelRenderer BottomMold5;

    public GaltMoldStationModel()
    {
        textureWidth = 64;
        textureHeight = 32;

        Table = new ModelRenderer(this, 0, 13);
        Table.addBox(0F, 0F, 0F, 16, 3, 16);
        Table.setRotationPoint(-8F, 15F, -8F);
        Table.setTextureSize(64, 32);
        Table.mirror = true;
        setRotation(Table, 0F, 0F, 0F);
        Leg2Shaft1 = new ModelRenderer(this, 0, 0);
        Leg2Shaft1.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg2Shaft1.setRotationPoint(-6F, 18F, 7F);
        Leg2Shaft1.setTextureSize(64, 32);
        Leg2Shaft1.mirror = true;
        setRotation(Leg2Shaft1, 0F, 0F, 0F);
        Leg2Shaft2 = new ModelRenderer(this, 0, 0);
        Leg2Shaft2.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg2Shaft2.setRotationPoint(-4F, 18F, 5F);
        Leg2Shaft2.setTextureSize(64, 32);
        Leg2Shaft2.mirror = true;
        setRotation(Leg2Shaft2, 0F, 0F, 0F);
        Leg2Shaft3 = new ModelRenderer(this, 0, 0);
        Leg2Shaft3.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg2Shaft3.setRotationPoint(-6F, 18F, 3F);
        Leg2Shaft3.setTextureSize(64, 32);
        Leg2Shaft3.mirror = true;
        setRotation(Leg2Shaft3, 0F, 0F, 0F);
        Leg2Shaft4 = new ModelRenderer(this, 0, 0);
        Leg2Shaft4.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg2Shaft4.setRotationPoint(-8F, 18F, 5F);
        Leg2Shaft4.setTextureSize(64, 32);
        Leg2Shaft4.mirror = true;
        setRotation(Leg2Shaft4, 0F, 0F, 0F);
        Leg4Shaft3 = new ModelRenderer(this, 0, 0);
        Leg4Shaft3.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg4Shaft3.setRotationPoint(-6F, 18F, -8F);
        Leg4Shaft3.setTextureSize(64, 32);
        Leg4Shaft3.mirror = true;
        setRotation(Leg4Shaft3, 0F, 0F, 0F);
        Leg4Shaft2 = new ModelRenderer(this, 0, 0);
        Leg4Shaft2.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg4Shaft2.setRotationPoint(-4F, 18F, -6F);
        Leg4Shaft2.setTextureSize(64, 32);
        Leg4Shaft2.mirror = true;
        setRotation(Leg4Shaft2, 0F, 0F, 0F);
        Leg4Shaft = new ModelRenderer(this, 0, 0);
        Leg4Shaft.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg4Shaft.setRotationPoint(-6F, 18F, -4F);
        Leg4Shaft.setTextureSize(64, 32);
        Leg4Shaft.mirror = true;
        setRotation(Leg4Shaft, 0F, 0F, 0F);
        Leg4Shaft4 = new ModelRenderer(this, 0, 0);
        Leg4Shaft4.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg4Shaft4.setRotationPoint(-8F, 18F, -6F);
        Leg4Shaft4.setTextureSize(64, 32);
        Leg4Shaft4.mirror = true;
        setRotation(Leg4Shaft4, 0F, 0F, 0F);
        Leg2Shaft = new ModelRenderer(this, 0, 0);
        Leg2Shaft.addBox(0F, 0F, 0F, 3, 6, 3);
        Leg2Shaft.setRotationPoint(-7F, 18F, 4F);
        Leg2Shaft.setTextureSize(64, 32);
        Leg2Shaft.mirror = true;
        setRotation(Leg2Shaft, 0F, 0F, 0F);
        Leg4Shaft1 = new ModelRenderer(this, 0, 0);
        Leg4Shaft1.addBox(0F, 0F, 0F, 3, 6, 3);
        Leg4Shaft1.setRotationPoint(-7F, 18F, -7F);
        Leg4Shaft1.setTextureSize(64, 32);
        Leg4Shaft1.mirror = true;
        setRotation(Leg4Shaft1, 0F, 0F, 0F);
        Leg1Shaft1 = new ModelRenderer(this, 0, 0);
        Leg1Shaft1.addBox(0F, 0F, 0F, 3, 6, 3);
        Leg1Shaft1.setRotationPoint(4F, 18F, 4F);
        Leg1Shaft1.setTextureSize(64, 32);
        Leg1Shaft1.mirror = true;
        setRotation(Leg1Shaft1, 0F, 0F, 0F);
        Leg1Shaft = new ModelRenderer(this, 0, 0);
        Leg1Shaft.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg1Shaft.setRotationPoint(5F, 18F, 7F);
        Leg1Shaft.setTextureSize(64, 32);
        Leg1Shaft.mirror = true;
        setRotation(Leg1Shaft, 0F, 0F, 0F);
        Leg1Shaft2 = new ModelRenderer(this, 0, 0);
        Leg1Shaft2.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg1Shaft2.setRotationPoint(7F, 18F, 5F);
        Leg1Shaft2.setTextureSize(64, 32);
        Leg1Shaft2.mirror = true;
        setRotation(Leg1Shaft2, 0F, 0F, 0F);
        Leg1Shaft4 = new ModelRenderer(this, 0, 0);
        Leg1Shaft4.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg1Shaft4.setRotationPoint(3F, 18F, 5F);
        Leg1Shaft4.setTextureSize(64, 32);
        Leg1Shaft4.mirror = true;
        setRotation(Leg1Shaft4, 0F, 0F, 0F);
        Leg1Shaft3 = new ModelRenderer(this, 0, 0);
        Leg1Shaft3.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg1Shaft3.setRotationPoint(5F, 18F, 3F);
        Leg1Shaft3.setTextureSize(64, 32);
        Leg1Shaft3.mirror = true;
        setRotation(Leg1Shaft3, 0F, 0F, 0F);
        Leg3Shaft1 = new ModelRenderer(this, 0, 0);
        Leg3Shaft1.addBox(0F, 0F, 0F, 3, 6, 3);
        Leg3Shaft1.setRotationPoint(4F, 18F, -7F);
        Leg3Shaft1.setTextureSize(64, 32);
        Leg3Shaft1.mirror = true;
        setRotation(Leg3Shaft1, 0F, 0F, 0F);
        Leg3Shaft = new ModelRenderer(this, 0, 0);
        Leg3Shaft.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg3Shaft.setRotationPoint(5F, 18F, -4F);
        Leg3Shaft.setTextureSize(64, 32);
        Leg3Shaft.mirror = true;
        setRotation(Leg3Shaft, 0F, 0F, 0F);
        Leg3Shaft2 = new ModelRenderer(this, 0, 0);
        Leg3Shaft2.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg3Shaft2.setRotationPoint(7F, 18F, -6F);
        Leg3Shaft2.setTextureSize(64, 32);
        Leg3Shaft2.mirror = true;
        setRotation(Leg3Shaft2, 0F, 0F, 0F);
        Leg3Shaft3 = new ModelRenderer(this, 0, 0);
        Leg3Shaft3.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg3Shaft3.setRotationPoint(5F, 18F, -8F);
        Leg3Shaft3.setTextureSize(64, 32);
        Leg3Shaft3.mirror = true;
        setRotation(Leg3Shaft3, 0F, 0F, 0F);
        Leg3Shaft4 = new ModelRenderer(this, 0, 0);
        Leg3Shaft4.addBox(0F, 0F, 0F, 1, 6, 1);
        Leg3Shaft4.setRotationPoint(3F, 18F, -6F);
        Leg3Shaft4.setTextureSize(64, 32);
        Leg3Shaft4.mirror = true;
        setRotation(Leg3Shaft4, 0F, 0F, 0F);
        BottomMold3 = new ModelRenderer(this, 20, 1);
        BottomMold3.addBox(0F, 0F, 0F, 2, 1, 2);
        BottomMold3.setRotationPoint(-3F, 13F, -1F);
        BottomMold3.setTextureSize(64, 32);
        BottomMold3.mirror = true;
        setRotation(BottomMold3, 0F, 0F, 0F);
        TopMold = new ModelRenderer(this, 22, 1);
        TopMold.addBox(-1F, 0F, 0F, 2, 4, 6);
        TopMold.setRotationPoint(4F, 11F, -3F);
        TopMold.setTextureSize(64, 32);
        TopMold.mirror = true;
        setRotation(TopMold, 0F, 0.2094395F, 0F);
        BottomMold = new ModelRenderer(this, 20, 1);
        BottomMold.addBox(0F, 0F, 0F, 4, 1, 6);
        BottomMold.setRotationPoint(-4F, 14F, -3F);
        BottomMold.setTextureSize(64, 32);
        BottomMold.mirror = true;
        setRotation(BottomMold, 0F, 0F, 0F);
        BottomMold1 = new ModelRenderer(this, 20, 1);
        BottomMold1.addBox(0F, 0F, 0F, 4, 1, 1);
        BottomMold1.setRotationPoint(-4F, 13F, -3F);
        BottomMold1.setTextureSize(64, 32);
        BottomMold1.mirror = true;
        setRotation(BottomMold1, 0F, 0F, 0F);
        BottomMold2 = new ModelRenderer(this, 31, 3);
        BottomMold2.addBox(0F, 0F, 0F, 4, 1, 1);
        BottomMold2.setRotationPoint(-4F, 13F, 2F);
        BottomMold2.setTextureSize(64, 32);
        BottomMold2.mirror = true;
        setRotation(BottomMold2, 0F, 0F, 0F);
        BottomMold4 = new ModelRenderer(this, 20, 1);
        BottomMold4.addBox(0F, 0F, 0F, 1, 1, 4);
        BottomMold4.setRotationPoint(-4F, 13F, -2F);
        BottomMold4.setTextureSize(64, 32);
        BottomMold4.mirror = true;
        setRotation(BottomMold4, 0F, 0F, 0F);
        BottomMold5 = new ModelRenderer(this, 20, 1);
        BottomMold5.addBox(0F, 0F, 0F, 1, 1, 4);
        BottomMold5.setRotationPoint(-1F, 13F, -2F);
        BottomMold5.setTextureSize(64, 32);
        BottomMold5.mirror = true;
        setRotation(BottomMold5, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Table.render(f5);
        Leg2Shaft1.render(f5);
        Leg2Shaft2.render(f5);
        Leg2Shaft3.render(f5);
        Leg2Shaft4.render(f5);
        Leg4Shaft3.render(f5);
        Leg4Shaft2.render(f5);
        Leg4Shaft.render(f5);
        Leg4Shaft4.render(f5);
        Leg2Shaft.render(f5);
        Leg4Shaft1.render(f5);
        Leg1Shaft1.render(f5);
        Leg1Shaft.render(f5);
        Leg1Shaft2.render(f5);
        Leg1Shaft4.render(f5);
        Leg1Shaft3.render(f5);
        Leg3Shaft1.render(f5);
        Leg3Shaft.render(f5);
        Leg3Shaft2.render(f5);
        Leg3Shaft3.render(f5);
        Leg3Shaft4.render(f5);
        BottomMold3.render(f5);
        TopMold.render(f5);
        BottomMold.render(f5);
        BottomMold1.render(f5);
        BottomMold2.render(f5);
        BottomMold4.render(f5);
        BottomMold5.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }


}
